version: "2.1"
services:
  jobmanager:
    image: flink:1.7.2-alpine
    container_name: jobmanager
    expose:
      - "6123"
      - "9249"
    ports:
      - "8081:8081"
      - "9250:9249"
    command: > 
        bash -c 'echo "metrics.reporter: prom" >> /opt/flink/conf/flink-conf.yaml
        && echo "metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter" >> /opt/flink/conf/flink-conf.yaml 
        && echo "metrics.reporter.prom.port: 9249" >> /opt/flink/conf/flink-conf.yaml 
        && echo "state.checkpoints.dir: /state" >> /opt/flink/conf/flink-conf.yaml 
        && cp /opt/flink/opt/flink-metrics-prometheus-*.jar /opt/flink/lib
        &&  /docker-entrypoint.sh jobmanager'
    environment:
      - JOB_MANAGER_RPC_ADDRESS=172.25.0.13
    volumes:
      - kafka_flink:/state
    networks:
      kafkanet:
        ipv4_address: 172.25.0.13

  taskmanager:
    image: flink:1.7.2-alpine
    container_name: taskmanager
    expose:
      - "6121"
      - "6122"
      - "9249"
    ports:
      - "9249:9249"
    depends_on:
      - jobmanager
    command: > 
        bash -c 'echo "metrics.reporter: prom" >> /opt/flink/conf/flink-conf.yaml
        && echo "metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter" >> /opt/flink/conf/flink-conf.yaml 
        && echo "metrics.reporter.prom.port: 9249" >> /opt/flink/conf/flink-conf.yaml 
        && echo "state.checkpoints.dir: /state" >> /opt/flink/conf/flink-conf.yaml 
        && cp /opt/flink/opt/flink-metrics-prometheus-*.jar /opt/flink/lib
        &&  /docker-entrypoint.sh taskmanager '
    environment:
      - JOB_MANAGER_RPC_ADDRESS=172.25.0.13
#    links:
#      - "jobmanager:jobmanager"
    volumes:
      - kafka_flink:/state
    networks:
      kafkanet:
        ipv4_address: 172.25.0.14

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    expose:
      - 2181
    ports:
      - "2181:2181"
    hostname: 172.25.0.15
    volumes:
      - kafka_zookeeper:/opt/zookeeper-3.4.13/data
    networks:
      kafkanet:
        ipv4_address: 172.25.0.15

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    command: [start-kafka.sh]
    expose:
      - "8080"
      - "9092"
#    ports:
#      - "9092:9092"
#      - "8080:8080"
#    hostname: kafka1
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.25.0.11
      KAFKA_ZOOKEEPER_CONNECT: 172.25.0.15:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_OPTS: -javaagent:/prometheus/jmx_prometheus_javaagent-0.3.1.jar=8080:/prometheus/kafka-0-8-2.yml 
    volumes:
      - ./kafka:/prometheus
      - kafka_kafka1:/opt/kafka_2.12-2.2.0/logs
    networks:
      kafkanet:
        ipv4_address: 172.25.0.11
    depends_on:
      - "zookeeper"

  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    command: [start-kafka.sh]
    expose:
      - "8080"
      - "9092"
#    ports:
#      - "9092:9092"
#      - "8080:8080"
#    hostname: kafka2
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.25.0.12
      KAFKA_ZOOKEEPER_CONNECT: 172.25.0.15:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_OPTS: -javaagent:/prometheus/jmx_prometheus_javaagent-0.3.1.jar=8080:/prometheus/kafka-0-8-2.yml 
    volumes:
      - ./kafka:/prometheus
      - kafka_kafka2:/opt/kafka_2.12-2.2.0/logs
    depends_on:
      - "zookeeper"
    networks:
      kafkanet:
        ipv4_address: 172.25.0.12

  kafka_manager:
    image: hlebalbau/kafka-manager:1.3.3.18
    container_name: kafka_manager
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "172.25.0.15:2181"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null
    networks:
      kafkanet:
        ipv4_address: 172.25.0.16

  prometheus:
    image: prom/prometheus:v2.8.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/flink.rules.yml:/etc/prometheus/flink.rules.yml
    networks:
      kafkanet:
        ipv4_address: 172.25.0.19

  prometheus2:
    image: prom/prometheus:v2.8.1
    container_name: prometheus2
    expose:
      - "9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/flink.rules.yml:/etc/prometheus/flink.rules.yml
    networks:
      kafkanet:
        ipv4_address: 172.25.0.17

  grafana:
    image: grafana/grafana:6.1.1
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=flink
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prometheus
    networks:
      kafkanet:
        ipv4_address: 172.25.0.18

networks:
  kafkanet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1

volumes:
  kafka_flink:
  kafka_zookeeper:
  kafka_kafka1:
  kafka_kafka2:

